name: SSH
on: 
    watch:
      types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id 
    steps:
     - name: Don't kill instace
       run: sleep 1h
